export { Login } from  "./Login"
export { Register } from "./Register"
export { Perfil } from "./Perfil"
export { Mensagem } from "./Mensagem"
export { CadMessage } from "./CadMensagem"
export { QrCode as ScreenQrCode } from "./QrCode" 
export { LocationMap as ScreenLocation} from "./LocationMap"
export { LocationMapOrDest as ScreenLocationMapOrDest} from "./LocationMapOrDest"
export { Acelerometro as ScreenAcelerometro } from "./Acelerômetro" 
export { Video as ScreenVideo } from "./Video"